openapi: "3.0.0"
info:
  description: "Daily Briefing Skill"
  version: "0.0.1"
  title: "Daily Briefing Skill"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "GPLv2"
    url: "https://www.gnu.org/licenses/gpl-2.0.en.html"

servers:
  - url: /api/v1
    description: "The APIs base path"

tags:
- name: "trigger"
  description: "A trigger for external event creation"

paths:
  /trigger/{userName}:
    parameters:
      - in: 'path'
        name: 'userName'
        required: true
        schema:
          type: 'string'

    post:
      tags:
      - "trigger"
      summary: "Trigger proactive event to happen right now!"
      description: "For demo purposes only"
      operationId: "api.skill.trigger"
      responses:
        204:
          description: "Triggered"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
